# Generated by Django 3.0.2 on 2020-01-19 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='owner',
            new_name='ownership',
        ),
    ]
