# Generated by Django 3.0.2 on 2020-01-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20200119_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='ownership',
            new_name='owner',
        ),
    ]
